// C++ headers
#include <string>
#include <boost/filesystem.hpp>

// Cadmium Simulator headers
#include <cadmium/modeling/dynamic_model_translator.hpp>
#include <cadmium/engine/pdevs_dynamic_runner.hpp>

// Time class header
#include <NDTime.hpp>

// Required for testing
#include "SupervisorConfig.hpp" // Generated by cmake.
#include "input_readers.hpp" // Input Reader Definitions.

// Atomic model to test.
#include "atomic_models/Landing_Routine.hpp"

using TIME = NDTime;

int main() {
	int test_set_enumeration = 0;

	const string i_base_dir = string(PROJECT_DIRECTORY) + string("/test/input_data/landing_routine/");
	const string o_base_dir = string(PROJECT_DIRECTORY) + string("/test/simulation_results/landing_routine/");

	do {
		// Input locations
		string input_dir						= i_base_dir + to_string(test_set_enumeration);
		string input_file_initial_state			= input_dir + string("/initial_state.txt");
		string input_file_landing_achieved		= input_dir + string("/landing_achieved.txt");
		string input_file_pilot_takeover		= input_dir + string("/pilot_takeover.txt");
		string input_file_start_mission         = input_dir + string("/start_mission.txt");
		string input_file_land					= input_dir + string("/land.txt");

		// Output locations
		string out_directory = o_base_dir + to_string(test_set_enumeration);
		string out_messages_file = out_directory + string("/output_messages.txt");
		string out_state_file = out_directory + string("/output_state.txt");

		if (!boost::filesystem::exists(input_file_initial_state) ||
			!boost::filesystem::exists(input_file_landing_achieved) ||
			!boost::filesystem::exists(input_file_pilot_takeover) ||
			!boost::filesystem::exists(input_file_start_mission) ||
			!boost::filesystem::exists(input_file_land)
			) {
			printf("One of the input files do not exist\n");
			return 1;
		}

        // Read the initial state of the model.
        fstream f;
        f.open(input_file_initial_state, ios::in);
        if (!f.is_open()) {
            printf("Failed to open initial_state file\n");
            return 1;
        }
        string initial_state_string;
        getline(f, initial_state_string);
        f.close();

		Landing_Routine<TIME>::States initial_state = Landing_Routine<TIME>::stringToEnum(initial_state_string);

		// Create the output location
		boost::filesystem::create_directories(out_directory.c_str());

		// Instantiate the atomic model to test
		shared_ptr<dynamic::modeling::model> landing_routine = dynamic::translate::make_dynamic_atomic_model<Landing_Routine, TIME, Landing_Routine<TIME>::States>("landing_routine", std::move(initial_state));

		// Instantiate the input readers.
		// One for each input
		shared_ptr<dynamic::modeling::model> ir_landing_achieved =
			dynamic::translate::make_dynamic_atomic_model<Input_Reader_Boolean, TIME, const char* >("ir_landing_achieved", input_file_landing_achieved.c_str());
		shared_ptr<dynamic::modeling::model> ir_pilot_takeover =
			dynamic::translate::make_dynamic_atomic_model<Input_Reader_Boolean, TIME, const char* >("ir_pilot_takeover", input_file_pilot_takeover.c_str());
		shared_ptr<dynamic::modeling::model> ir_land =
			dynamic::translate::make_dynamic_atomic_model<Input_Reader_Mavlink_Mission_Item, TIME, const char* >("ir_land", input_file_land.c_str());
        shared_ptr<dynamic::modeling::model> ir_start_mission =
                dynamic::translate::make_dynamic_atomic_model<Input_Reader_Int, TIME, const char* >("ir_start_mission", input_file_start_mission.c_str());

		// The models to be included in this coupled model
		// (accepts atomic and coupled models)
		dynamic::modeling::Models submodels_TestDriver = {
			ir_landing_achieved,
			ir_pilot_takeover,
			ir_land,
            ir_start_mission,
			landing_routine
		};

		dynamic::modeling::Ports iports_TestDriver = { };

		dynamic::modeling::Ports oports_TestDriver = { };

		dynamic::modeling::EICs eics_TestDriver = {	};

		// The output ports will be used to export in logging
		dynamic::modeling::EOCs eocs_TestDriver = { };

		// This will connect our outputs from our input reader to the file
		dynamic::modeling::ICs ics_TestDriver = {
			dynamic::translate::make_IC<iestream_input_defs<bool>::out,Landing_Routine<TIME>::defs::i_landing_achieved>("ir_landing_achieved", "landing_routine"),
			dynamic::translate::make_IC<iestream_input_defs<bool>::out,Landing_Routine<TIME>::defs::i_pilot_takeover>("ir_pilot_takeover", "landing_routine"),
			dynamic::translate::make_IC<iestream_input_defs<message_landing_point_t>::out,Landing_Routine<TIME>::defs::i_land>("ir_land", "landing_routine"),
			dynamic::translate::make_IC<iestream_input_defs<int>::out,Landing_Routine<TIME>::defs::i_start_mission>("ir_start_mission", "landing_routine")
		};

		shared_ptr<dynamic::modeling::coupled<TIME>> TEST_DRIVER = make_shared<dynamic::modeling::coupled<TIME>>(
			"TEST_DRIVER", submodels_TestDriver, iports_TestDriver, oports_TestDriver, eics_TestDriver, eocs_TestDriver, ics_TestDriver
		);

		/*************** Loggers *******************/
        static ofstream out_messages;
        static ofstream out_state;

		out_messages = ofstream(out_messages_file);
		struct oss_sink_messages {
			static ostream& sink() {
				return out_messages;
			}
		};
		out_state = ofstream(out_state_file);
		struct oss_sink_state {
			static ostream& sink() {
				return out_state;
			}
		};

		using state = logger::logger<logger::logger_state, dynamic::logger::formatter<TIME>, oss_sink_state>;
		using log_messages = logger::logger<logger::logger_messages, dynamic::logger::formatter<TIME>, oss_sink_messages>;
		using global_time_mes = logger::logger<logger::logger_global_time, dynamic::logger::formatter<TIME>, oss_sink_messages>;
		using global_time_sta = logger::logger<logger::logger_global_time, dynamic::logger::formatter<TIME>, oss_sink_state>;

		using logger_supervisor = logger::multilogger<state, log_messages, global_time_mes, global_time_sta>;

		dynamic::engine::runner<NDTime, logger_supervisor> r(TEST_DRIVER, { 0 });

		r.run_until_passivate();
		test_set_enumeration++;
	} while (boost::filesystem::exists(i_base_dir + std::to_string(test_set_enumeration)));

	fflush(nullptr);
	string path_to_script = PROJECT_DIRECTORY + string("/test/scripts/simulation_cleanup.py");
	string path_to_simulation_results = PROJECT_DIRECTORY + string("/test/simulation_results");
	if (system("python3 --version") == 0) {
		string command = "python3 " + path_to_script + string(" ") + path_to_simulation_results;
		system(command.c_str());
	} else if (system("python --version") == 0) {
		string command = "python " + path_to_script + string(" ") + path_to_simulation_results;
		system(command.c_str());
	} else {
		cout << "\nPython is not installed!\n";
	}

	return 0;
}
