// C++ headers
#include <string>
#include <filesystem>

// Cadmium Simulator headers
#include <cadmium/modeling/dynamic_model_translator.hpp>
#include <cadmium/engine/pdevs_dynamic_runner.hpp>

// Time class header
#include <NDTime.hpp>

// Required for testing
#include "SupervisorConfig.hpp" // Generated by cmake.
#include "input_readers.hpp" // Input Reader Definitions.

#include "coupled_models/Takeoff.hpp"

using TIME = NDTime;

// Used for oss_sink_state and oss_sink_messages
ofstream out_messages;
ofstream out_state;

// Model output ports
struct o_request_aircraft_state : public out_port<bool> {};
struct o_start_mission : public out_port<bool> {};
struct o_start_monitoring : public out_port<bool> {};
struct o_update_gcs : public out_port<std::string> {};

int main() {
	int test_set_enumeration = 0;

	const std::string i_base_dir = std::string(PROJECT_DIRECTORY) + std::string("/test/input_data/takeoff/");
	const std::string o_base_dir = std::string(PROJECT_DIRECTORY) + std::string("/test/simulation_results/takeoff/");

	do {
		// Input locations
		string input_dir						= i_base_dir + to_string(test_set_enumeration);
		string input_file_aircraft_state		= input_dir + std::string("/aircraft_state.txt");
		string input_file_perception_status		= input_dir + std::string("/perception_status.txt");
		string input_file_start_supervisor		= input_dir + std::string("/start_supervisor.txt");

		// Output locations
		string out_directory					= o_base_dir + to_string(test_set_enumeration);
		string out_messages_file				= out_directory + std::string("/output_messages.txt");
		string out_state_file					= out_directory + std::string("/output_state.txt");

		if (!filesystem::exists(input_file_aircraft_state) ||
			!filesystem::exists(input_file_perception_status) ||
			!filesystem::exists(input_file_start_supervisor)) {
			printf("One of the input files do not exist\n");
			return 1;
		}

		// Create the output location
		filesystem::create_directories(out_directory.c_str());

		// Instantiate the coupled model to test
		Takeoff t = Takeoff();
		shared_ptr<dynamic::modeling::coupled<TIME>> takeoff = make_shared<dynamic::modeling::coupled<TIME>>("takeoff", t.submodels, t.iports, t.oports, t.eics, t.eocs, t.ics);

		// Instantiate the input readers.
		// One for each input
		shared_ptr<dynamic::modeling::model> ir_aircraft_state =
				dynamic::translate::make_dynamic_atomic_model<Input_Reader_Aircraft_State, TIME, const char* >("ir_aircraft_state", input_file_aircraft_state.c_str());
		shared_ptr<dynamic::modeling::model> ir_perception_status =
				dynamic::translate::make_dynamic_atomic_model<Input_Reader_Boolean, TIME, const char* >("ir_perception_status", input_file_perception_status.c_str());
		shared_ptr<dynamic::modeling::model> ir_start_supervisor =
				dynamic::translate::make_dynamic_atomic_model<Input_Reader_Start_Supervisor, TIME, const char* >("ir_start_supervisor", input_file_start_supervisor.c_str());

		// The models to be included in this coupled model
		// (accepts atomic and coupled models)
		dynamic::modeling::Models submodels_TestDriver = {
				ir_aircraft_state,
				ir_perception_status,
				ir_start_supervisor,
				takeoff
		};

		dynamic::modeling::Ports iports_TestDriver = { };

		dynamic::modeling::Ports oports_TestDriver = {
				typeid(o_request_aircraft_state),
				typeid(o_start_mission),
				typeid(o_start_monitoring),
				typeid(o_update_gcs)
		};

		dynamic::modeling::EICs eics_TestDriver = {	};

		// The output ports will be used to export in logging
		dynamic::modeling::EOCs eocs_TestDriver = {
				dynamic::translate::make_EOC<Takeoff_defs::o_request_aircraft_state,o_request_aircraft_state>("takeoff"),
				dynamic::translate::make_EOC<Takeoff_defs::o_start_mission,o_start_mission>("takeoff"),
				dynamic::translate::make_EOC<Takeoff_defs::o_start_monitoring,o_start_monitoring>("takeoff"),
				dynamic::translate::make_EOC<Takeoff_defs::o_update_gcs,o_update_gcs>("takeoff")
		};

		// This will connect our outputs from our input reader to the file
		dynamic::modeling::ICs ics_TestDriver = {
				dynamic::translate::make_IC<iestream_input_defs<message_aircraft_state_t>::out,Takeoff_defs::i_aircraft_state>("ir_aircraft_state", "takeoff"),
				dynamic::translate::make_IC<iestream_input_defs<bool>::out,Takeoff_defs::i_perception_status>("ir_perception_status", "takeoff"),
				dynamic::translate::make_IC<iestream_input_defs<message_start_supervisor_t>::out,Takeoff_defs::i_start_supervisor>("ir_start_supervisor", "takeoff")
		};

		shared_ptr<dynamic::modeling::coupled<TIME>> TEST_DRIVER = make_shared<dynamic::modeling::coupled<TIME>>(
				"TEST_DRIVER", submodels_TestDriver, iports_TestDriver, oports_TestDriver, eics_TestDriver, eocs_TestDriver, ics_TestDriver
		);

		/*************** Loggers *******************/
		out_messages = ofstream(out_messages_file);
		struct oss_sink_messages {
			static ostream& sink() {
				return out_messages;
			}
		};

		out_state = ofstream(out_state_file);
		struct oss_sink_state {
			static ostream& sink() {
				return out_state;
			}
		};

		using state = logger::logger<logger::logger_state, dynamic::logger::formatter<TIME>, oss_sink_state>;
		using log_messages = logger::logger<logger::logger_messages, dynamic::logger::formatter<TIME>, oss_sink_messages>;
		using global_time_mes = logger::logger<logger::logger_global_time, dynamic::logger::formatter<TIME>, oss_sink_messages>;
		using global_time_sta = logger::logger<logger::logger_global_time, dynamic::logger::formatter<TIME>, oss_sink_state>;

		using logger_supervisor = logger::multilogger<state, log_messages, global_time_mes, global_time_sta>;

		dynamic::engine::runner<NDTime, logger_supervisor> r(TEST_DRIVER, { 0 });

		r.run_until_passivate();
		test_set_enumeration++;
	} while (filesystem::exists(i_base_dir + std::to_string(test_set_enumeration)));

	fflush(nullptr);
	string path_to_script = PROJECT_DIRECTORY + std::string("/test/scripts/simulation_cleanup.py");
	string path_to_simulation_results = PROJECT_DIRECTORY + std::string("/test/simulation_results");
	if (system("python3 --version") == 0) {
		string command = "python3 " + path_to_script + std::string(" ") + path_to_simulation_results;
		system(command.c_str());
	} else if (system("python --version") == 0) {
		string command = "python " + path_to_script + std::string(" ") + path_to_simulation_results;
		system(command.c_str());
	} else {
		cout << "\nPython is not installed!\n";
	}

	return 0;
}
