#ifndef COMPONENT_MACROS_HPP
#define COMPONENT_MACROS_HPP

#define COMP_ID_PERCEPTION_SYSTEM 2
#define COMP_ID_MISSION_MANAGER 3
#define COMP_ID_OFFLINE_PATH_PLANNER 4
#define COMP_ID_DETECT_AND_AVOID 5
#define COMP_ID_BOSS 6

#define SUPERVISOR_SIG_ID_START_SUPERVISOR 1
#define SUPERVISOR_SIG_ID_PERCEPTION_STATUS 2
#define SUPERVISOR_SIG_ID_WAYPOINT 3
#define SUPERVISOR_SIG_ID_LP_RECEIVE 4
#define SUPERVISOR_SIG_ID_PLP_ACHIEVED 5

#endif /* COMPONENT_MACROS_HPP */